// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koteyzimkijigtrpnabq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvdGV5emlta2lqaWd0cnBuYWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTY4NjksImV4cCI6MjA2Mzk5Mjg2OX0.BSFXTijH7r6FkFvh-DVbJAoCLUphvfp7cdeq82DNFvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);